# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FulcrumSync
                                 A QGIS plugin
 Link Fulcrum to QGIS throught the REST API
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-01-21
        copyright            : (C) 2021 by NGIS
        email                : stafford.smith@ngis.com.au
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FulcrumSync class from file FulcrumSync.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .fulcrum_sync import FulcrumSync
    return FulcrumSync(iface)
