# -*- coding: utf-8 -*-
#  TODO: attributes are not imported into temp feature layers
#  TODO: Allow user configurable API Key
#  TODO: move apps list population to only happen once Get Apps List 'pushButton' is pressed


"""
/***************************************************************************
 FulcrumSync
                                 A QGIS plugin
 Link Fulcrum to QGIS throught the REST API
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-01-21
        git sha              : $Format:%H$
        copyright            : (C) 2021 by NGIS
        email                : stafford.smith@ngis.com.au
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.core import QgsProject, QgsVectorLayer, QgsJsonUtils, QgsWkbTypes, QgsFields, edit
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis.gui import QgsMessageBar
from qgis.utils import iface

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .fulcrum_sync_dialog import FulcrumSyncDialog
import os.path
import requests

###############################
    # Custom functions as static methods
def getAppsList(API_TOKEN):

    url = "https://api.fulcrumapp.com/api/v2/forms.json"

    querystring = {"schema":"true","page":"1","per_page":"20000"}

    headers = {
        "Accept": "application/json",
        "X-ApiToken": API_TOKEN
    }

    response = requests.request("GET", url, headers=headers, params=querystring)
    jsonResponse = response.json()

    appsList = []
    for form in jsonResponse['forms']:
        appsList.append(form['name'])

    return(appsList)




class FulcrumSync:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'FulcrumSync_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Fulcrum Sync')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('FulcrumSync', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/fulcrum_sync/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Fulcrum Sync'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Fulcrum Sync'),
                action)
            self.iface.removeToolBarIcon(action)


    def getSelectedLayer(self):
        selectedLayer = self.dlg.listWidget.selectedItems()[0].text()
        iface.messageBar().pushMessage("DEBUGGING", selectedLayer)
        self.selectedLayer = selectedLayer
    

    def getGeoJsonFromSelectedLayer(self):

        
        # selectedLayer = self.dlg.listWidget.selectedItems()[0]
        url = "https://api.fulcrumapp.com/api/v2/query"

        tableSelector = f"SELECT * FROM \"{self.selectedLayer}\""
        iface.messageBar().pushMessage("DEBUGGING", tableSelector)
        querystring = {"q":tableSelector,"format":"geojson","headers":"false","metadata":"false","arrays":"false","page":"1","per_page":"20000"}

        headers = {
            "Accept": "application/json",
            "X-ApiToken": self.API_TOKEN
        }

        response = requests.request("GET", url, headers=headers, params=querystring)
        # jsonResponse = response.json()

        self.createLayerFromGeojson(response.text)
        iface.messageBar().pushMessage("DEBUGGING", response.text)



    def createLayerFromGeojson(self, geoj):
        # PyQGIS has a parser class for JSON and GeoJSON
        feats = QgsJsonUtils.stringToFeatureList(geoj, QgsFields(), None)
        # if there are features in the list
        if len(feats) > 0:
            # define the geometry type of the layer
            geom_type = feats[0].geometry().type()
            if geom_type == QgsWkbTypes.PointGeometry:
                geotype = "MultiPoint"
            elif geom_type == QgsWkbTypes.LineGeometry:
                geotype = "MultiLineString"
            elif geom_type == QgsWkbTypes.PolygonGeometry:
                geotype = "MultiLinePolygon"
            else:
                iface.messageBar().pushMessage("DEBUGGING", "Geometry Type Not Declared in Geojson")
            # create a new memory layer with the features
            vl = QgsVectorLayer(geotype, self.selectedLayer, "memory")
            # vl = QgsVectorLayer("MultiPoint", "geojson_layer", "memory")
            with edit(vl):
                vl.addFeatures(feats)
                vl.updateExtents()
            # add this brand new layer
            QgsProject.instance().addMapLayer(vl)
        else:
            print("no features found in the geoJSON")


    def run(self):
        """Run method that performs all the real work"""

        ###############################
        # API token here temporarily...
        # TODO: move this to be provided by user in some config file, or from dialog and saved somewhere locally.
        self.API_TOKEN = "2b6d6363d014e69d8eff078c093c0a06df71f68a45cd88123780386de4eced40e7a317c8ddc56e24"

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = FulcrumSyncDialog()

        
        ###########################################
        # Get the list of Fulcrum Apps and display       
        appsList = getAppsList(self.API_TOKEN)
        self.dlg.listWidget.clear()
        self.dlg.listWidget.addItems(appsList)

        ############################################
        # Set up the connections between the dialog clicks and the methods
        self.dlg.listWidget.itemClicked.connect(self.getSelectedLayer)
        self.dlg.pushButton_3.clicked.connect(lambda: self.getGeoJsonFromSelectedLayer())


        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            pass
            
            




